language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install -r pip-req.txt
  - python -m nltk.downloader punkt
# command to run tests
script:
  - python -m unittest discover -v
