Hyah!
Out in the land 
Where the menare tough as cactus 
Out in the land wherethe wild, wild west was won 
Out in the landof the desperado 
If you're softas an avocado 
Yeehaw!You're guacamole, son 
Oh, home,this ain't it, pal 
Home, home,home on the range 
Home, home,better go git, pal 
You ain'thome on the range 
Out in the land wherethe weak are target practice 
Out in the land wherethey shoot the mild and meek 
Out where the badare a whole lot badder 
If you're the typewith a nervous bladder 
Yip! Yow!Your saddle's gonna reek 
'Cause you ain'thome on the range 
Cowboy,you're really up a creek 
Home, home,home on the range 
Home, home,home on the range 
Home, home,home on the range 
Howdy, sheriff!
Home on the range.
Once upon a time,I had a home on the range.
But not anymore.
Well, it's no usecryin' over spilled milk.
Speakin' of which, that's me.
I'm the cow.
Yeah, they're real.
Quit staring.
I'm sort of between homesright now.
I lost my old place...
thanks to the meanest bunch ofcattle rustlers in the west__
Alameda Slimand the Willie Brothers gang.
Oohee 
Somehow,they stole the whole herd...
right outfrom under our noses...
and then they disappearedwithout a trace.
After that...
poor old Abner couldn'tafford to keep the place...
or me, either, for that matter.
Well, no matter how badthings get...
there's probably somebodyworse off.
That guy, for instance.
Hey, Maggie.
Take a look at your new home.
Hey! A dairy farm?
Now we're talkin'!
Hope it's not one of themfatfree places.
I know a place 
Pretty as pie 
Out where the river bend 
Hits upwith the end of the sky 
It's left of Nebraska 
And over a crest 
On a little Patch of Heavenway out west 
Everything's green 
Know what I mean? 
Darlin', it's quitethe sweetest sight 
That you ever done seen 
Ain't nothin' muchout there 
Just life at its best 
On a little Patch of Heavenway out west 
Bees by the dozen 
Are buzzin' real peaceful 
Every bluebonnet,doggone it, smells nice 
Eventhe tumblin' tumbleweed 
Slows downto match your speed 
On my tiny half an acreof paradise 
Darlin', I swear 
Once you been there 
There ain't a viewbeneath the blue 
That could ever compare 
The only thing missing 
Is you as my guest 
On a little Patch of Heavenway out west 
Why don't you come visit? 
There's room in the nest 
On that littlePatch of Heaven 
Way out weeee... 
...eeeest 
Hey, that's my boy.
Can hog! Can hog!
Don't yell at me.
Oh. The call of duty.
Why don't you handle this one,Grace?
It's time I gave youmore responsibility on the farm.
Really?
Thanks, Mrs. C.I'll make you proud.
Can hog! Can hog!
Get off my case,little cocktail wieners!
Whoa, whoa!
I'm sensing a lotof negative energy here.
That's our can, and Jeb took it.
And now he says it's his can.
Now, let's not playthe shame and blame game.
This is an organic problem,and there's a holistic solution.
You don't get this wholefarm concept, do you, sister?
Kill the goat!
Give it! Get the can!
Ahem. We're sorry, Mrs. Caloway.
Piggies,why can't you leave Jeb alone?
Yeah! Why can't you?
The poor old goatneeds peace and quiet.
That's right! I need it!
So, run along,and take your can with you.
Yeah, you take that can and__
Hey! Whoa! Come back here,you little bacon bits!
Jeb, don't you haveenough cans of your own?
Uh, no, not really.
I'd be happy to take her in,Abner.
There's always roomfor one more.
Well, thanks, Pearl.
I gotta warn you, though.
She's__heh heh__she's a bit headstrong.
Oh, now, don't you worry, Abner.
I'm sure she'll fit right in.
So long, Pearl.You take care, now.
Mrs. Caloway! Oh! Mrs. Caloway!Mrs. Calo__
Mrs. Caloway,there's a newcomer at the gate.
Not now, Audrey. But it's a great big__
Everybody? This here is Maggie.
Threetime winnerof the Golden Udder Award...
and the originalMiss Happy Heifer.
A show cow?
On Patch of Heaven?
Now, I want y'allto make her feel right at home.
You hear me?
Hey, thanks, everybody.
It's great to be herein Patch of Heaven.
Now, don't everybody speakat one time.
What is this,the frozen food section?
Is this thing on?
Ahem.Good morning, uh, Margaret.
What a wonderful surprise...
to find a fellow bovinejoining the ranks.
Phony.
I'm Mrs. Caloway. Hi.
And this is Grace. Hi.
No applause and trophies here,I'm afraid.
Just the fruitsof our good, honest labor.
Hi.
Workin' stiffs, huh?
Boy, I remember those days.
Wow! You're the biggest cowI have ever saw.
Well, if you're in charge,I'll take that as a compliment.
Uh__ And if you're not...
I guessI'll just have to sit on you.
Mom!
Hey, I'm only kidding!
Say, what is this you've gotjammed up in your ear?
Here, have an apple, kid.
Don't go near any luaus, though.
Wait a minute.
I got somethin' stuck in my ear.
This one's for me.
Ahh! That was good.
Awesome!
Do it again! Do it again!
Come on, come on!Do it again! Do it again!
Oh! That's so cool!
Maggie's some fun, isn't she?
Ohh.Teaching pigs to throw food.
As if they weren'tsloppy enough.
I'm goin' long!
Heh heh heh.
Dagnabit, Buck, slow down!
OK, who's up for a gameof tincan tag?
Hey!That can is a family heirloom.
Whoever wins is gettin'a free tetanus shot! OK?
Superstar comin' through!
Awesome!
No autographs, please. I got your autograph, pal! Ow!
Who's the hotshot?
Oh, it's Buck. Puh! City slicker.
Oh! Whoa! Whoa!Dagnabit, Buck!
Take it easy.This ain't no rodeo.
Why, good morning, Sam.Heh heh.
Is that ornery horsegettin' away from you again?
Oh, uh, howdy, Pearl.
I came out to bring youanother bank notice.
This one'll be the last.
You know, every timeI get a weak harvest...
they send meone of these here notices.
They'll get their moneysoon enough.
It's a whole newshootin' match now, Pearl.
The bank's callin' ineverybody's debt.
They're losin' moneysomethin' fierce...
with all the cattlemengoin' under.
I'm tellin' you, if they don'tget their money in three days...
they're gonna auction offPatch of Heaven.
What?
No.
But...they can't take my place.
Why, I've been herethrough twisters, blizzards.
Sam, uh...
Sam, this is my home.
I'm sorry, Pearl.I'm truly sorry.
Yeah, well...
"sorry"just ain't gonna save my farm.
Well, Buck,I hope you're proud of yourself.
As a matter of fact, I am.Thank you for checking.
You know, Pearl,it don't have to be this way.
You've got the best livestockin the county.
All you gotta do...
is just sell offa few of these critters__
Stop right there, Sam.
They're family.You don't sell family.
Hohohold your horses, Pearl.
Now you get,before I start using words...
no good woman should ever use.
Don't bust your gusset, woman! Go on, Sam!
It is still my property!Now get!
I said, get!
I was just tryin' to help!
That sure took the starchright out of me.
I am sorry, girls.
I'm just plum out of ideas.
Well, I think we all knowwhat happens now.
Well, I think we all knowwhat happens now.
Uh, Jeb, don't start. Now we all get eaten.
Jeb? What? What?
You don't think people in towneat animals?
But who would eat a chicken?Heh heh.
Come on, guys. There must besomething we can do.
What? What could we do?
This just isn't fair. Fair!
Good call, Curly!
Ollie. Ollie.
Uh, what is?
Listen. What would you sayif I told you...
that you could win big money__
and seebeautiful downtown Chugwater__
if you went to the County Fair?
Thank you for your input, but__
Come on! Let the new cow talk!
New cow! New cow! New cow!
Come on, Mrs. C. You've gota real goodlookin' bunch here.
I see some real potential.
Aw, shucks.
Now, the fair is two weeks away.
I say we go to town, butter upthat sheriff's horse...
and get himto give us more time.
What are we waitin' for, Maggie?Let's go.
That's right.What do you say, Caloway?
Bah! Absolutely not.
I will not abandon Pearlin her hour of need...
for such a ridiculous plan.
She would be devastatedif she found us missing.
As far as I'm concerned,that's not an option.
All right. Suit yourself.
Come on, Grace.We've got a farm to save.
Oh, you'll have to excuse her.She's just a little tense.
Tense. What's her specialty,sour cream?
Going to town.
Of all the illconceived I__
Now, don't look at meso crossly.
I know whatyou're going to say__
that Maggie and Gracewill need someone...
with my eye for detail...
to keep themon the straight and narrow.
Say no more. I'll go.
Now, tut tut. No mushygoodbyes, my little ones.
You know how I getabout overly emotional displays.
Ahem. Ladies?
Mrs. C.
Well,what made you change your mind?
I'd rather not talk about it. It's a chick thing.
Good luck, girls!
See ya! Bye!
They're stew meat. Hurry back!
She'll becomin' 'round the mountain 
She'll be comin''round the mountain 
She'll be comin' 'round... 
She better hurry uparound that mountain...
'cause I cannot take thismuch longer.
Maggie, may I be frank?
Only if you let me wear the hat.
Ahem. Lowbrow remarksmay work for you...
but we preferthe gentle approach.
Well, she betterstick a sock in it soon.
The vulturesare starting to circle.
Hey, she's not dying!
You sure? We could wait around!
...no, nothing,when she sees Grandma 
No more food for her 
We'll keep you posted!
False alarm, Clem!
Roger dodger, out like the wind!
Hey, Maggie, Mrs. C?How do we find...
the sheriff's officewhen we get into town?
Elementary, my dear Grace.
If we find Buck,we find the sheriff.
That horse is a legendin his own mind.
Ah ha ha ha ha!
Ah ha ha ha ha!
So, you thinkyou got the drop on me?
Well, think again.
Wahoo!
Wah! Wah!
Wah!
Yahhoo! Hyah!
Haaay! Jump back! Kiss myself!
Buck. Earth to Buck? Buck!
It's your move.
Ohh...great.
You were sleepfighting again.Almost threw a shoe.
Ohh. Sorry. Heh.
It just__it seems likeall the other horses...
are out there fighting bad guysand takin' names!
Uhh! Who put this here?
Oh, Buck,this ain't no Dodge City...
but we get our shareof excitement.
Hey, sheriff!
Been waitin' a long timeto give you this!
Telegram!
Oh, howdy, Morse.What you got there?
Hmm. "Got Evil Eye Joe. Stop.
"Bringing him today. Stop.
Have money ready. Signed, Rico."
Ha! Oh, yeah!Rico caught another one already.
Might as well give himthe key to my safe.
You hear that, Rusty?Rico's comin'.
Yeah, Rico.I'm old. I ain't deaf.
Boy, wouldn't that be the life?
Ridin' with Rico,cleanin' up the west.
Kickin' badguy behind!Whoo! Wahyah!
Watch out, sucker!
All right, girls.We're goin' in.
Look! There's no fences.
What keeps the peoplefrom roaming?
They appear to be domesticated.
It doesn't feel dangerousat all.
It's perfectly safe.Quiet as a farm at milkin' time.
What was that?
It's a gunfight!
Aah! Hit the dirt! Who lives like this?
What do we do? What do we do?
Look,there's a star on that door!
That must bethe sheriff's office.
Move, ladies! Move!
Swivel your hips, ooh!Give 'em a grind 
Shimmy and shakeand leave your troubles be__ 
Ha ha ha! Ha ha ha!
Whoa! Get those cows off the stage!
Maybe we came at a bad time.
Charge!
Ha ha ha! Ha ha ha!
How dare you? Oh!
Whoaohoh!
Daddy? Son!
I say! Aah!
Aah! Oh! Ow! What did I do?
That does it!
Hoof it on out of here, ladies!
Go on! Oh, come back!
That was the best dang showwe ever had!
Aw, you've been on the trailtoo long, you old coot.
Ohh. What kind ofsheriff's office is that?
Dancing girls, gambling...
Ha! How does he everget any work done?
If that's the sheriff's office,this town rocks.
Well, if it isn'tthree maids amilkin'.
You girls a little farfrom home, aren't ya?
Well, if it isn'tthe phony express.
We want a word with youabout this.
What's that? What is that?
I believe you left thison our farm.
Wai__whoa, whoa, whoa, whoa.Wait a minute.
The place went bankrupt.Your farm is history.
Don't you heifers get it?
Hold on, you two!
Give us two more weeks...
and we'll have at leastsixty bucks in prize money to__
Ahahah. You got three daysto pay or get on your way.
And sixty bucks don't cut it.
Looks like you need about...
Hmm, I'd say...
seven hundred and fifty of 'em.
But, Maggie, where are wegonna get all that money?
Well, maybe Maggiecan just pull it out of her ear.
Hey, watch it, Caloway.
Rico. Rico.
Rico. Rico.
Who is that?
Sorry.
Don't you know a herowhen you see one, huh?
That's Rico...
the best dang bounty hunterthis side of the Pecos.
I could guessfrom here to tomorrow...
but I don't knowhow you do it, Rico.
Mmf! Where's my money?
Well, all right,I got it right here for you.
Hey, they're giving awayfree money!
Oh! Maggie!
So, who else is out there?
The only varmint left...
is that lowdown,goodfornothin' Alameda Slim.
Cattle rustler.
What's the bounty? $750.
I got it!
Why don't we go nabthat Alameda Slim...
and use the reward moneyto save the farm?
Oh, that is a sensible idea.
I knew you'd love it!
Tch. Don't they have sarcasmwhere you come from?
Oh, wake up and smellthe alfalfa! It's perfect!
I'm gonna need a fresh horse.
Hmm, a horse. A horse.
Let me think.
I reckon you'd wanta fast horse, huh? Real fast?
Course, he'd also haveto be able to go...
for dayswithout food or drink...
stealthy,surefooted in any terrain...
Well, huh...
Look at me! What about that horse?
What, you mean Buck here?
Eee! Boy, I don't know.
Buck's fast, all right,but he's kind of a handful.
He'll do. Well, suit yourself.
Hey, Rusty!
Rico's saddle!I'm wearing Rico's saddle!
I'm wearing Rico's saddle!
Great. I'll leave you two alone.
Ohh, oh, no. No, no, no.
There is no wayin heaven or earth...
that cows can catch an outlaw.
Look, all we've got to do...
is follow this chuck wagonto a cattle drive.
Ahh. And then, you see...
we let the bad guys come to us.
Oh! We'veno reason to believe...
this chuck wagon is heading offto a cattle drive.
Hey, Tommy!Have fun on that cattle drive!
All right, then. Mmhmm.
I think it isheaded toward a cattle drive.
Shh. We are not followingthis wagon, and that is final.
Come on, Caloway. It'll be fun!
Did you just hit me? Kinda.
Well, stop it. Why?
Because I don't like it.
Oh, no. Not the hat.
What? What about the__
All right, all right...
violence is not goingto solve anything.
Why don't we all takea deep cleansing breath__
Yaah! Yaah!
Hey, now! Mud wrestling!
Ha ha! Hey, hey!Watch the saddle!
What in tarnation?
Maggie, for the last time...
I will not be ropedinto this scheme.
Come on, you crazy heifers!
Come on! Dagnabit!
Hey, partner,curb your livestock.
This town is clean!
Giddyup!
Ack!
Not exactly what I had in mind,but this'll work.
Well, it doesn't work for me!
Adios, Buck.Take care of Rico now.
Hasta la vista, heifers!Hoo hoo!
Oh, give me a home 
Oh, give me a home 
Where the buffalo roam 
And the deer__ahem__and the antelope plaaay 
Where seldom is heard 
A discouraging word 
And the skiesare not cloudy all day 
Home, home on the range 
Sold! What was that?
It's a farm auction, ladies.
And that's the lastof the furniture.
The final itemto be auctioned...
is this pieceof real property...
known heretoforeas the Dixon farm.
Do I hear 425? 425!Do I hear 450? 450?
What's going to happento the cow who lived there?
She'll be OK.
How do you know? You're lookin' at her.
This was your farm? Mmhmm.
We had, like, a family, too,you know.
What happened? Alameda Slim happened.
Sold to Mr. Yancy O'Del!
Pleasuredoing business with you.
Cattle drive. Told ya.
You both owe me a dollar.
Step lightly, girls.
The male of the speciescan be extremely hostile.
Oh, come on, Caloway.
It's not like they haven'tseen a cow before.
Hey, Barry.
What? Huh? Check it out.
Ooh, dairy cows!
Oh, hey, how's it going?
Oh, hello. Let me guess.You're a Taurus.
Look, just keep movingand avoid eye contact.
Pardon me, but what arethree lovely ladies like you...
doing on a drive like this?
Just ignore them,and perhaps they'll go away.
Oh, they seem like nice guys.Maybe they can help us.
Why, sure we can help you.
Maybe we can help each other.
Hmm? Hmm?
Look, loverbull,we're here strictly on business.
Ooh, sounds pretty exciting.What kind of business?
We're looking for a cattlerustler named Alameda Slim.
Grace! Shh! Grace! Shh!
Hey, it doesn't hurt to ask.
Slim? Oh ho ho ho!
Why, Slim's justa scary bedtime story...
to get little calves to behave.
What was that?
It must be Slim and the Willies.
Slim and the Willies?
Don't worry, darlin'.I'll protect you.
You have exactly two secondsto remove your hoof...
before I snap it offat the knee.
Oh, uh, sorry, ma'am.I thought you were the blonde.
Ooh!
Come on, girls.It's time to lose these ropes.
Where you going? Hoyah! Hyah!
Maggie, I'm stuck. Look out!
Hahh!
It's payback time.
Cover me! With what?
Howdy, Slim. Howdy, Slim.
Quiet, you fools.We've got work to do.
Now listen up.
There are crooksin this here west 
Who have claimedto be the best 
And they think they wrotethe book on how to rustle 
Well,as good as they may be 
Not a one's as good as me 
And I barely have to movea single muscle 
They call me mean, boys 
Depraved and nasty, too 
And they ain't seen, boys 
The cruelest thing I do 
You see Iyodeladleeedleidleodle 
The sweetest way of rustlin'yet devised 
'Cause when Iyodeladleeedleidleodle 
Why, looky,how them cows get hypnotized 
He don't prod,he don't yell 
Still he drivesthem dogies well 
Which ain't easywhen your chaps are labeled 
XXXXL 
Yes, if yer lookin'from a bovine point of view 
I sure canyodeladleeedleidle 
Yodeladleeedleidle 
Yodeladleeedleidleoo 
Here we go, boys!5,000 cattle in the side pocket!
Maggie! Mrs. Caloway!Snap out of it!
A sound that cattletruly take to heart 
Yeah, I canyodeladleeedleidle 
Yodeladleeedleidelodle 
And smack my big old rumpif that ain't art 
He don't rope,not a chance 
He just puts 'emin a trance 
He's a pioneer pied piperin tengallon underpants 
Yep, I'm the realriproarin' deal 
To those who moo 
Thanksto my yodeladleeedleidle 
Yodeladleeedleidle 
I got cattleout the old wazoo, heh heh! 
'Cause I canyodeladleeedleidleoo 
Yodeladleeedleidleoo 
Whoa. Ho, boy.
Rico, if you'd just beena second earlier...
you'd have had that rustlerdead to rights.
You boys see anythingbefore I got here?
Yeah, we sure did there, Rico.
We were justsettin' down to supper...
when all of a suddenthe lights went out.
All right, what part of"cover me" didn't we understand?
You guys OK? I don't know.
I feel like I was dreaming.
Yeah. Slim started singing...
and all of a suddenI lost track of everything.
Singing? That didn't soundlike singing to me.
And, you know,I have perfect pitch.
Uh, yes. Grace,about your perfect pitch__
Not now, Maggie. All right, show's over!
Oh, no.
You're interferingwith official police bidness!
Ha. Be right with you, big guy.
Buck is on the case.You know. Whoo!
Don't embarrass mein front of my partner. Please!
You and he are partners?
So, how does that work exactly?
I mean, do you get to ride himon odd days or even?
Hey! He chose me specifically...
because I have skillsthat are essential...
to capturing our quarry.
Ha ha ha!
Whoo! Smush! Oof!
You boys headed back to town?
Yes, sir. We got to go filea report with the sheriff.
Give him back his horse.
This one's too skittisharound cows.
And that, girls,is what makes me and Rico...
equal parts ofone lean mean crimefighting__
machine?
Well, there it is, then.
Well, well, well, stud.
Now, I'm no professional...
but I'd say the onlymano a mano you'll be doing...
is in your dreams.
Oh, look out, Buck.
He's making a moveon your left flank. Kaboosh!
Maggie! Grace!Leave that poor animal alone.
Buck,I realize you're very upset...
but if you'd liketo join our group...
and help us bring in Slim,we'd be happy to have you.
However, there are a few...
angermanagement issueswe need to discuss.
I wouldn't helpyou bossy bovines...
if my life depended on it!
You see, that's justwhat I'm talking about.
Grace! Bye.
Come on, girls. Hmm.
Let's go get Slim.
"Come on, girls,let's go get Slim."
Cudchewing heifers.
Huh. I can catch that Slim withone hoof tied behind my back.
Wait a minute. Why don't l?
Yes! Partner or no partner,that's what I'ma do. Hey!
Ba ba ba ba ba 
Hold the horse now.
Aw, forget it.
Definitely bipolar.
Move it, sister!Hero passing on the left!
Hey, watch it. Where are you going, hotfoot?
I'm gonna go nab that rustler...
and show RicoI got what it takes...
so say goodbye to your farm,girls, because Slim is mine.
It's hero time!
Watch out now! Hey! Get back!
Jump back! Kiss myself! Whoo!
Da da yoo 
Oh, this isa fine kettle of fish.
How can we compete with that?
Look at the bright side, Mrs. C.
Don't forget aboutour secret weapon.
Secret weapon?
Who better to catcha cattle thief than a cow?
Yeah, even you can't arguewith that kind of logic.
OK, maybe you can.
You know, Grace...
Maggie does so loveyour singing.
How about a song?
I'm gonna get you for this.
Ha ha! 5,000 Texas longhorns.
Not bad for one night's work.
Pick a color.
I said,not bad for one night's work.
What? Thank you.
And judging by the ear mark...
I'd say these are the lastof Big Mike Donald's herd.
Big Mike Donald had a farm?
EIEI__IEIEI__
Ohh... Ohh...
That's right. He had a farm.Heh heh heh.
Now that all his cash cowshave disappeared...
that poor sap'sgonna be flat broke.
Perfect time for a certainupstanding land owner...
to step inand take all the land.
Aah! Who are you?
What did you dowith Uncle Slim?
Put up your dukes,Mr. Fancy Britches.
Aahaahaahaahaahaah!
It's me. Hello?
This hereis the disguise I use...
to sneak intoall them auctions...
and buy all the land,you brainless monotone monkeys.
Shoot, you got to be the richestland baron in the west.
Yes, but the partthat really warms my heart...
is watching those homesteaderssuffer.
Back in the day, I worked...
the highfalutinest ranchesyou ever seen...
but those stuckup ranch bossescouldn't appreciate my talents.
Maybe they just didn't likeyour singing.
My singing?
Songbirds sing.
Saloon gals sing.
Little bitty snotnosedchildren sing.
I yodel!
And yodeling is an art!
Well, maybe they justdidn't like your yodeling.
He didn't mean it, Uncle Slim.
Everybody likes yodeling.
Hmm?
Why, it's one of the funniest,cornball, goofy, silly sounds...
in the whole west.
Yaah! Aah! Yaah!
Uh, Gil? Uhhuh?
Am I correct in assumingthat each and every time...
we brought a herd backto this secret lair...
you've managed to sitin the exact same spot...
blocking that choicepiece of property from my view?!
This is my comfy place.
What? Aah!
It's calledPatch of Heaven, Uncle Slim.
Goes on auctionThursday morning.
Perfect. Pencil it in.
Thursday morning__right afterwe sell off this herd.
But it's justa little old dirt farm.
Ah, what's the difference?
When you're talking revenge,every last acre counts.
I don't get it.
Weren't the cowssupposed to come back?
Daddy, what's going to happenif they don't come back?
Oh, but they are coming back.
Hogwash! We all knowthey're never coming back.
What? Ooh! Ooh!
You don't know that, Jeb.
Everybody knows that bovines...
are the most intelligent,crafty animals in the west.
Yeah. He's right, you know.
It doesn't take a cowto figure out...
they sawthe writing on the wall...
and flown the coopwhile the getting was good.
What?
Oh, no!They tricked us and deserted us!
No, no. AudAudrey.
Excuse me. Excuse me.
Excuse me!
Oh, uh, let's not forgetwho we're talkin' 'bout.
Audrey, remember whenGrace helped you figure out...
why you crossed the road?
And, Jeb, Miss Calowayknew just what to do...
when your head got stuckin that spittoon.
Get off my case!
And Maggiewas gonna make us all winners.
I truly believethere ain't nothin'...
those three cows can't do.
Well, whatever they're gonna do,they better do it soon.
I'm so very sorry, Pearl.
It's a real shame. It is.
Ollie,I don't know what's worse__
Losing my farmto the highest bidder...
or knowing that__that my girlsare lost and alone out there.
Yeehaw! Come on, girls.
EitherI'm getting good at this...
or his scentis getting stronger.
Go get him, Maggie.Look out, Slim!
No. It can't be. We're on your trail!
Hoo hoo!
This has Buckwritten all over it.
We're not gonna letthis dumb old trick stop us.
Sooner or later, all these pathswill hook up, and then...
Oh, no, the tracks!
Hurry up, girls.Don't lose that trail.
What trail?I can't see anything.
Look out!
Oh! Flash flood!
Get to high ground!
Oh. Maggie!
Maggie!
No! Come on, girls,we can't give up!
Maggie, that's enough.The minute this lets up...
we're heading straight hometo Patch of Heaven.
But what about catching Slimand collecting the reward?
We never had a prayer...
of catching Slimin the first place.
This whole ridiculous plan...
is just so you can get revengeon those cattle rustlers.
Hey!For your information, duchess...
this whole ridiculous planis about us saving our farm.
Huh. Our farm might've hada fighting chance...
until you came along.
What's that supposed to mean?
Strutting around withyour vulgar showcow behavior.
Look, I was just having__
Wasting our timeon your foolish plans.
Through the years,Patch of Heaven...
has survived every hardshipthat nature can dish out...
but you, Maggie...
are the biggest catastropheto ever hit our farm.
Well, if that's the wayyou feel about it...
maybe we should just goour separate ways.
Now, that's the firstgood idea you've ever had.
Fine! Fine!
Fine! Fine!
Yeah. Fine.
It's not like your farm...
was ever gonna feel like hometo me anyways.
Rain is pourin' down 
Like the heavensare hurtin' 
Seems like it's been darksince the devil knows when 
How do you go onnever knowing for certain 
Will the sunever shine again? 
Feels like it's been yearssince it started to thunder 
Clouds are campin' outin the valley and glen 
How do you go on whenyou can't help but wonder 
Will the sunever shine again? 
What if the rainkeeps fallin'? 
What if the skystays gray? 
What if the windskeep squallin' 
And never go away? 
Maybe soon the stormwill be tired of blowin' 
Maybe soonit all will be over, amen 
How do you go on ifthere's no way of knowin'? 
Will the sun ever shine? 
Wish I could say 
Send me a sign 
One little ray 
Lord,if you're listenin' 
How long until then? 
Will the sun ever shine 
Again? 
Maggie. Maggie. Maggie.
Wake up. Check, please!
It tasted a lot betterin my sleep.
Well, I supposeyou'll be off now.
Mmhmm. Where will you go?
Oh, probably check outthe Grand Canyon.
See Utah before I die.
Wait a minute. Where's Grace?
Hi, there.Boy, am I glad you guys are up.
Hey, come look at this.
What on earth?Where did all this come from?
Hey, it's green, it's leafy,and it's free. Shut up and eat.
Good morning, ladies.
I see you're alreadytucked into your appetizer.
Never knew a pretty ladythat didn't have an appetite.
Oh, now, see here, you ruffian__
He's not a ruffian,Mrs. Caloway.
He's a genuine desert shaman__our very own wise man.
Shaman, chef, chief cook,and bottle washer.
I'm a jackrabbit of all tradesand at your service.
Folks around these partscall me Lucky Jack.
Yep, they used to comefrom miles around...
just to get one rubof my lucky rabbit's foot.
Whoo! Dagnabit!
This happens all the time.Now, where was l?
Ah. Voila.
Now let me justget this on the fire...
and it'll be ready directly.
Mmhuh. Ow! Yow!
Look, we don't eat meat.
It's kind of likea professional courtesy.
Perhaps we'll dine with yousome other time.
You see, Grace and lare returning to our farm...
to say our last goodbyes.
Yeah. We need closure.
Well, I can sympathize there,sister, I truly can.
Until recently,l, too, had a home.
Echo Mine it was called.
Us jackrabbits lived therefor generation after generation.
Till some landgrabbing banditmoved in...
and flushed us outlike yesterday's oatmeal.
Ahem. Excuse us. My good fellow,we must be on our way.
Wait! There he is!
Slim! You meanthis nogood varmint...
is hiding out in Echo Mineright now?
Without a doubt. Maggie, what are you thinking?
Look, I got a score to settlewith that rhinestone fat boy...
and nothing to lose.
But it'll be dangerous goingafter Slim all by yourself.
Hey, I got the rabbit.
That's not all you got, Maggie.You got us.
Oh, no. No, no, no. No.
We are sticking to our planand going home.
Hold on, you two.
As strange as this sounds,Grace is actually making sense.
Thank you. You want the money...
and I want to get evenwith Slim.
The three of us go together,and we're sure to get him.
Once you collect the reward,I'll walk out your front gate...
and I'll stay out of it forever.Deal?
Your powers of persuasionare uncanny. Deal.
Ha! Bovine bounty hunters!Now I've seen everything.
Let's get moving, ladies.
Let's get moving, ladies.
Time for an undergroundsmackdown. Yeehaw!
Out in the land wherethe heroes meet their makers 
Out in the land wherethe hale and hearty fall 
Out where the fearlessget the shudders 
Justice is here,and it's wearing udders 
Yeehaw!The cows are walkin' tall 
Home, home,this ain't it, pal 
Home, home,home on the range 
Home, home,better go git, pal 
Home, home,home on the range 
OK, boys, let's gothrough it one last time.
Who am I? Uncle Slim?
Correct! Heh.
Now, I put on my hat...
then I put on my spectacles__
Aah! Hey! Who're you? Where's Uncle Slim?
Ohh! It's still me!
Can't you stupidsack of hammers get it right?
Oh, the everpunctualMr. Weaseley.
OK, everybody make way...
for the big manin black market livestock.
Hey, who're you?
All right, come on!
Move it, Bessie, orI'll tan your hides right here.
I__hey, hey, hey!Watch the suit! Watch the suit!
Feast your eyes.
5,000 cows on the barrelheadas promised, Mr. Weaseley.
The name's Wesley.
So, Slim, what do you saywe get a move on...
and load these cash cowsonto the train A.S.A.P., huh?
Let's go.
Yes, yes, of course. Just assoon as I finish counting. Hmm.
Lucky Jack, you did it!We're here!
Well,I take my hat off to you, Jack.
But you've got us herein one piece.
Well, seein' is believin'.
And I don't believe what I see.
Oh, it's Buck!
Stallion of the Cimmoron.
I'm supposed to be herejust in case...
one of the horses get tired.
Cows only.
Look, friend, you don'tunderstand my situation.
No, you don't understand...
so I'll say it again.
The only crittersthat get by me are cows.
Cows only.
Oh, come on!Look, cut me a break.
Now what?
Aww, what are you doing here?
Ha ha! Sorry we're late.We got separated from the herd.
Right this way, little lady.
Tell 'em Junior sent you.
Ohhh...
Howdy, partner! Ahem.
Nice hat, ma'am. Oh! Cheeky devil.
Excuse me, reject.Coming through.
Oh! Hey, what gives?!
How comethey got to go through?
They're cows.
What?!But what about the rabbit?
Well, obviously,he was with the cows.
Ha! I'm with the cows, too!
Yeah! Hey! Hey, cows! Wwait up!
You got to tell this guyyou know me!
See, Junior, we're old friends!
Come on, Margie! Uh, Gretchen!Miss, uh__uh, Hat Cow!
Come on,it's your old pal Buck, see?
Buck...Buck...
Oh, Buck!
Nah, doesn't ring a bell.
No, no, no, wait!Hey, come back! No!
Hang on__hang on a second.Heh heh heh.
They're just kidding.You see, if you could__
Oh, hey! Hey!Hey, cows! Cows! Oof!
Don't make me hurt you.
Heh heh.
Rico.
I gotta go, but let's throw onthe old feedbag sometime.
Stay cool.Ha ha ha! It's hero time.
So what's the plan?
Well, let's see...
You two get his attentionwhile I sneak up behind him...
and thenI'll knock him into the cart...
and then we'll rope him upand wheel him to justice!
And for extra measure...
how about we conk himon the noggin with this?
You go, cowgirl!That's usin' the old hat.
Whoa, whoa, whoa!Now, you lost me here, missy.
Look, Jack, it's simple.
Cart, smack, rope, roll,justice. Come on, Jack, focus.
Now is not the time to getall scatterbrained and flaky.
Oh, good, I'm not too late.
Sorry. Still stakin' outyour quarry, huh?
Yeah, pretty much. Why?
Listen, I came to warn you, oneequine to another, about Rico.
As soon as he nabsthat rustler...
he's gonna be in a big hurryto collect that reward.
So? So?!
Once he catches his man, that'swhen the horsewhip comes out...
and he's not shyabout using it, either!
Horsewhip? Horsewhip!
And not only are yougonna be carrying Rico...
but that rustler as well.
Have you seen that guy?He's huge!
What should I do?
Run! OK.
Yeah, run like the wind,partner, and save yourself!
I'm going!
Go on, take off! Fade!Ride into the sunset!
All righty, I'm outta here! Aah! Scram!
OK, thanks, buddy!I owe you one!
Godspeed, my friend!
So long, sucker! Ha ha!
He must be takin' stupid lessonsfrom that buffalo.
1,420... 4,334...
Can't you moronscount to yourselves?
Come on.
Gotta start all over!
There he is. Come on, let's go!
Hold on!
You're both forgettingSlim's hypnotic control...
over thosewith less than perfect pitch.
Jack, I hope you can forgive me.
For what, missy? Aah! For that.
Now, you watch it there, toots!
Grace, how practical!
Done countin'!
What do we got? 4,997.
What? Huh? Wait, wait, what?
I thought you said 5,000 even.
Of course I did. Gil must'vejust miscounted, that's all.
Huh?
There's one up there!
The others can't be far behind.
Just you watch.
You're gonna like this.Yodeling's an art.
Huh?
Ha ha ha!What's the deal, Slimbo?
Maybe she wasn't an art lover.
Philistine!
Shut up, you greenhorns!
A bovine ain't been bornthat can resist my charms.
Ahem.
Watch your back, Uncle Slim!
Got you!Where do you think you're going?
Now, Jack! OK!
What in the rootin'tootin'blazes is goin' on here?!
Uncle Slim! Uncle Slim!
Let's get outta here!
Aah! Come back here, dog meat!
Jackpot! We got him now!
Well done! Watch out!
It's Buck!
Hey, Casey Jones...
grab the billsand fire up the getaway express!
Uncle Slim! Uncle Slim!
I gave up clown collegefor this?
Aah! Aah! Ooh! Mama!
It's Slim! I got Slim!Rico's gonna be so proud of me!
Thank you!
Whoa! Whoa! Ooh! Leave me alone!
Yaaahhoohoohooey!
Sorry. Uncle Slim! Uncle Slim!
Quick, girls, in here! Ooh!
Hey!
Huh?
That was Rico!
What in blue blazes?
I'll knock youinto next Tuesday!
Come back here!
Whoa! Whoa! You're going down!
Junior! Junior!
Oh! Whoa! Junior!
Juniooor! Whoohah!
Get this off of me! Uncle Slim! Uncle Slim!
Rico's saddle!I'm wearing Rico's saddle!
Uncle Slim! Oof! Ohh!
Surprise! Oof!
We made it, girls!We made it!
Three cheers! Hiphiphooray!
Ladies, we got company!
Whoa! Stop! Stop! Hit the brake!
Look out!
Yaah! Dagnabit!
I guess I gotta do everythingaround here myself!
Call me crazy, but I thinkthese cows got it in for me.
Maybe they just don't likeyour singing.
Shut up! Ahem.
Mr. Weaseley,my money, if you please.
Heh heh heh. I was justkeeping it safe for you, Slim.
Sure you were.
Protecting my investmentsis what I pay this fellow for.
Mr. Weaseley, let me present...
the most traitorous,doublecrossin' gun for hire...
that I've ever had the pleasureto call partner__Rico.
You're too kind, boss.
No, it can't be.
His reputation asa bounty hunter is wellknown...
but lately he's been doinga little moonlighting...
and covering my tracks.
Rico's going to see youto the border...
so that nothing else goes wrong.
Now, if you'll all pardon me...
there'sa little Patch of Heaven...
on the auction blockthis morning.
He's going to buy our farm!
Adios! Yeehaw!
I don't knowhow you got here, skittish...
but stick with me,and you may get to like...
the other side of the law.
Get on there! Hyah!
All right, come on! Come on!
Move it, Bessie! Get in there!
Hurry up!You don't want to be late...
for that big roundupin the sky!
Hah! Skittish, whoa!
Whoa! Whoa! Whoa! Whoa!
Get in there!Come on, you stupid cows!
Come on!
Lovely.Now get the engine fired up...
and let's make tracks.
Huh?
Make a break for it,ladies! Run!
Whoa! Hah! Skittish, whoa!
Buck, have you gone crazy?!
Now, that's entirely possible!Yo!
Or maybe I just figured outwho the real heroes are!
Wait! What if this issome kind of trick?
Whoo! Whassah!
Oh, this isn't a trick!It's a miracle! Come on!
So you thinkyou got the drop on me...
well, think again! Hyah!
Whassah!
This is useless.
Let's put our heads together.More brains and less brawn.
All right!
OK, Caloway, fetch!
Kaboosh! Hyah!
Ha! Lucky shot!
Mother of mercy.Is this the end of Rico?
Wow! Bravo!
Bravo! You stopped Rico cold!
Aw, shucks. T'weren't nothin'.
Fat lot of good it done us.
Alameda Slimhas already flown the coop.
She's right.
Unless we sprout wings, we'llnever make it back in time.
I can't believewhat I'm hearing.
This traingoes right by Patch of Heaven.
What is in the cudyou've been chewin'?
How are we supposedto drive that thing?
How? How? I'll tell you how!
The same way we walked offthe farm into the unknown.
The same way we fought offthose burly barmaids.
And the same way we bravedthe western wilderness...
without the benefitof food or water.
We caught Slim once,and we shall do it again!
Who's with me?
Get out of here, you bulls!Head for the hills! Whoo!
Let's get it on! Cows rule!
Howdy, darlin'! Down here!
Yeah! Look__look down!Hello there!
Oh, no!
I got two words for you guys__cold shower!
We don't have timefor this nonsense!
We have a farm to save!
Well, maybe we can help you. Maybe we can help each__oof!
Other! Ohh!
Bye!Come up and see us sometime!
Grace!
Oh, no!It's the Morning Express!
There's a switch up ahead!
Way ahead of you, pops!Hop on!
Come on, mule! Let's ride!
Yeehaw!
Ha! Ha!
Whoa! Oh! Whoa! Whoa!
Roadhogs!
See you back at the farm, girls!
Good luck!
This happens all the time.
Sold!All property and livestock...
Sold!All property and livestock...
formerly known asPatch of Heaven...
is hereby soldto Mr. Yancy O'Del.
Pleasure doing businesswith you. Heh heh heh.
O'Del's the name,foreclosure's the game.
Well,just set yourself over yonder.
Sign this deed,and the property is all yours.
Much obliged, sheriff.
Ha ha ha!
There it is! Home and hearth!
And a holy hallelujahof a curve!
Oh, quick, the brakes! No time for that!
But won't we jump the tracks? We are makin' our own tracks!
This is going to be messy!
Hee hee hee! The whole territorybelongs to me. Huh?
Five cents for these chicks.
Come on, now,do I hear two cents?
Behind you! Bbehind you!
Whoa! Whoa! Hold your britches!Come on, now!
Whoa! Run for your lives!
Watch yourself!
What's the idea of crashingyour train on my property?
What? Uh...
It can't be!
Hold it right there!
Piggies, it's time to open upa can of whoophide!
Unh! Who the__Oof! Ow! Aah!
Oh! Get away from there! Aah!
Oh, come on! Ow! Oof!
You wanna get nuts?Let's get nuts!
It's Alameda Slim!
You think you've won?
It ain't overtill the fat man sings!
Alameda Slim,you're under arrest.
Nobody messeswith Pearl's girls!
Say, girls, got milk? Buck!
Just kidding.
Take him away, boys!Hope you like stripes.
Pearl, your cows can't do muchwith Slim's reward money.
Think you can findsome use for it?
Whooeee! My farm is saved!
Where's Maggie?
I can't believe she just left.
I'm gonna miss her.
So shall l, Grace.
Her brash manner,her bullheadedness.
She risked her life for us,and who are we but strangers?
We were privileged to know her.She was a cow like no other!
Right down to her appallingbodily eruptions.
Ahh, that was good! Maggie!
I was just havingone for the road...
when I heardall the nice stuff...
you guys were saying about me.
You know, maybe I couldhang around a while.
How about forever? Oh!
Hmm.Well, it's your call, Caloway.
Is this barnyard big enoughfor the both of us?
Only if you let me wear the hat.
Yeehaw!
Come on, move your hides, girls.
Last one to the barnsleeps standing up!
OK, everyone, big smiles!
OK, everyone, big smiles!
"So it was that Alameda Slim...
"the most notoriousand feared cattle rustler...
was apprehended and unmaskedby three unusual dairy cows. "
Hey! Dagnabit, Jeb!
How many times I got to tell youto wait your turn?
How many timeshave I got to tell you...
to get out of my barrel__
Hey, dagnabit! You ornery ol'__
It's so nice that Jebfinally found a friend.
Here they come, everybody!
Well done! Ha ha ha!
Well, hi ho, ladies!
Hey, Barry, three queens,two kings, hmm?
Full house.
And the joker is wild.
Oh, yeah.
Darlin', I swear 
Once you been there 
There ain't a viewbeneath the blue 
That could ever compare 
Hyah! Hohaa!
The only thing missing 
Is you as my guest 
On a little Patch of Heavenway out west 
Why don't you come visit? 
There's room in the nest 
Yeehaw!
On that littlePatch of Heaven 
Way out west 
Come with me 
Let's go wander 
Far beyondthe wild blue yonder 
Out where stars roam free 
Though the journey'sfar from breezy 
Stick with me,I'll make it easy 
You can depend on me 
Yeah, there'sa long road before us 
And it's a hard road,indeed 
But, darlin', I swear 
I'll get us there 
Whereverthe trail may lead 
Once we crossthat far horizon 
Lifeis bound to be surprisin' 
But we'll take itday by day 
Never mindthe wind and weather 
If we walk that trailtogether 
Somehow we'll find our way 
Yeah, there's a long roadbefore us 
And it's a hard road,indeed 
But, darlin', I vow 
We'll get through somehow 
Whereverthe trail may lead 
Can't tell youwhen we'll be there 
It may take all our lives 
We're headed forthat great unknown 
We'll soon be walking freethere 
Till that day arrives 
At least we won't betravelin' alone 
And there'sa long road before us 
And it's a hard road,indeed 
But, darlin', don't fear 
'Cause I'll be right here 
To give youthe strength you need 
And through the whole ride 
I'll be by your side 
Wherever the trailmay lead 
La la la la 
La la la 
La la la 
La la la 
La la la 
When you're sad 
When you're feeling low 
When you're hurt 
And don't know where to go 
Think of me 
There I'll be 
Anytime you need a friend 
When you're down 
And your luck runs out 
Or if you're in troubleor in doubt 
It's OK 
It's OK 
Turn my way 
Anytime you need a friend 
When you're scared 
I will stay with you 
When you feelyou're fallin' 
I'm there for you 
When your heart breaks 
I'll ease your aches 
Whatever it takes 
I'm in 
I'm in 
Anytime you need a friend 
La la la 
La la la 
La la la 
La la la 
All our lives 
Anywhere we are 
Anywhere we are 
Just reach out 
I'll never be too far 
Come what may 
There I'll stay 
Anytime you need a friend 
When you're scared 
I will stay with you 
When you feelyou're fallin' 
I'm here for you 
When your heart breaks 
I'll ease your aches 
Whatever it takes 
I'm in 
Whatever it takes 
Anytime you need a friend 
La la la 
La la la 
Anytime 
Anytime you need 
A friend 