Hyah!
¤ Out in the land ¤
¤ Where the men|are tough as cactus ¤
¤ Out in the land where|the wild, wild west was won ¤
¤ Out in the land|of the desperado ¤
¤ If you're soft|as an avocado ¤
¤ Yeehaw!|You're guacamole, son ¤
¤ Oh, home,|this ain't it, pal ¤
¤ Home, home,|home on the range ¤
¤ Home, home,|better go git, pal ¤
¤ You ain't|home on the range ¤
¤ Out in the land where|the weak are target practice ¤
¤ Out in the land where|they shoot the mild and meek ¤
¤ Out where the bad|are a whole lot badder ¤
¤ If you're the type|with a nervous bladder ¤
¤ Yip! Yow!|Your saddle's gonna reek ¤
¤ 'Cause you ain't|home on the range ¤
¤ Cowboy,|you're really up a creek ¤
¤ Home, home,|home on the range ¤
¤ Home, home,|home on the range ¤
¤ Home, home,|home on the range ¤
Howdy, sheriff!
Home on the range.
Once upon a time,|I had a home on the range.
But not anymore.
Well, it's no use|cryin' over spilled milk.
Speakin' of which, that's me.
I'm the cow.
Yeah, they're real.
Quit staring.
I'm sort of between homes|right now.
I lost my old place...
thanks to the meanest bunch of|cattle rustlers in the west__
Alameda Slim|and the Willie Brothers gang.
¤ Oohee ¤
Somehow,|they stole the whole herd...
right out|from under our noses...
and then they disappeared|without a trace.
After that...
poor old Abner couldn't|afford to keep the place...
or me, either, for that matter.
Well, no matter how bad|things get...
there's probably somebody|worse off.
That guy, for instance.
Hey, Maggie.
Take a look at your new home.
Hey! A dairy farm?
Now we're talkin'!
Hope it's not one of them|fatfree places.
¤ I know a place ¤
¤ Pretty as pie ¤
¤ Out where the river bend ¤
¤ Hits up|with the end of the sky ¤
¤ It's left of Nebraska ¤
¤ And over a crest ¤
¤ On a little Patch of Heaven|way out west ¤
¤ Everything's green ¤
¤ Know what I mean? ¤
¤ Darlin', it's quite|the sweetest sight ¤
¤ That you ever done seen ¤
¤ Ain't nothin' much|out there ¤
¤ Just life at its best ¤
¤ On a little Patch of Heaven|way out west ¤
¤ Bees by the dozen ¤
¤ Are buzzin' real peaceful ¤
¤ Every bluebonnet,|doggone it, smells nice ¤
¤ Even|the tumblin' tumbleweed ¤
¤ Slows down|to match your speed ¤
¤ On my tiny half an acre|of paradise ¤
¤ Darlin', I swear ¤
¤ Once you been there ¤
¤ There ain't a view|beneath the blue ¤
¤ That could ever compare ¤
¤ The only thing missing ¤
¤ Is you as my guest ¤
¤ On a little Patch of Heaven|way out west ¤
¤ Why don't you come visit? ¤
¤ There's room in the nest ¤
¤ On that little|Patch of Heaven ¤
¤ Way out weeee... ¤
¤...eeeest ¤
Hey, that's my boy.
Can hog! Can hog!
Don't yell at me.
Oh. The call of duty.
Why don't you handle this one,|Grace?
It's time I gave you|more responsibility on the farm.
Really?
Thanks, Mrs. C.|I'll make you proud.
Can hog! Can hog!
Get off my case,|little cocktail wieners!
Whoa, whoa!
I'm sensing a lot|of negative energy here.
That's our can, and Jeb took it.
And now he says it's his can.
Now, let's not play|the shame and blame game.
This is an organic problem,|and there's a holistic solution.
You don't get this whole|farm concept, do you, sister?
Kill the goat!
Give it!| Get the can!
Ahem.| We're sorry, Mrs. Caloway.
Piggies,|why can't you leave Jeb alone?
Yeah! Why can't you?
The poor old goat|needs peace and quiet.
That's right! I need it!
So, run along,|and take your can with you.
Yeah, you take that can and__
Hey! Whoa! Come back here,|you little bacon bits!
Jeb, don't you have|enough cans of your own?
Uh, no, not really.
I'd be happy to take her in,|Abner.
There's always room|for one more.
Well, thanks, Pearl.
I gotta warn you, though.
She's__heh heh__|she's a bit headstrong.
Oh, now, don't you worry, Abner.
I'm sure she'll fit right in.
So long, Pearl.|You take care, now.
Mrs. Caloway! Oh! Mrs. Caloway!|Mrs. Calo__
Mrs. Caloway,|there's a newcomer at the gate.
Not now, Audrey.| But it's a great big__
Everybody? This here is Maggie.
Threetime winner|of the Golden Udder Award...
and the original|Miss Happy Heifer.
A show cow?
On Patch of Heaven?
Now, I want y'all|to make her feel right at home.
You hear me?
Hey, thanks, everybody.
It's great to be here|in Patch of Heaven.
Now, don't everybody speak|at one time.
What is this,|the frozen food section?
Is this thing on?
Ahem.|Good morning, uh, Margaret.
What a wonderful surprise...
to find a fellow bovine|joining the ranks.
Phony.
I'm Mrs. Caloway.| Hi.
And this is Grace.| Hi.
No applause and trophies here,|I'm afraid.
Just the fruits|of our good, honest labor.
Hi.
Workin' stiffs, huh?
Boy, I remember those days.
Wow! You're the biggest cow|I have ever saw.
Well, if you're in charge,|I'll take that as a compliment.
Uh__| And if you're not...
I guess|I'll just have to sit on you.
Mom!
Hey, I'm only kidding!
Say, what is this you've got|jammed up in your ear?
Here, have an apple, kid.
Don't go near any luaus, though.
Wait a minute.
I got somethin' stuck in my ear.
This one's for me.
Ahh! That was good.
Awesome!
Do it again! Do it again!
Come on, come on!|Do it again! Do it again!
Oh! That's so cool!
Maggie's some fun, isn't she?
Ohh.|Teaching pigs to throw food.
As if they weren't|sloppy enough.
I'm goin' long!
Heh heh heh.
Dagnabit, Buck, slow down!
OK, who's up for a game|of tincan tag?
Hey!|That can is a family heirloom.
Whoever wins is gettin'|a free tetanus shot! OK?
Superstar comin' through!
Awesome!
No autographs, please.| I got your autograph, pal! Ow!
Who's the hotshot?
Oh, it's Buck.| Puh! City slicker.
Oh! Whoa! Whoa!|Dagnabit, Buck!
Take it easy.|This ain't no rodeo.
Why, good morning, Sam.|Heh heh.
Is that ornery horse|gettin' away from you again?
Oh, uh, howdy, Pearl.
I came out to bring you|another bank notice.
This one'll be the last.
You know, every time|I get a weak harvest...
they send me|one of these here notices.
They'll get their money|soon enough.
It's a whole new|shootin' match now, Pearl.
The bank's callin' in|everybody's debt.
They're losin' money|somethin' fierce...
with all the cattlemen|goin' under.
I'm tellin' you, if they don't|get their money in three days...
they're gonna auction off|Patch of Heaven.
What?
No.
But...they can't take my place.
Why, I've been here|through twisters, blizzards.
Sam, uh...
Sam, this is my home.
I'm sorry, Pearl.|I'm truly sorry.
Yeah, well...
"sorry"|just ain't gonna save my farm.
Well, Buck,|I hope you're proud of yourself.
As a matter of fact, I am.|Thank you for checking.
You know, Pearl,|it don't have to be this way.
You've got the best livestock|in the county.
All you gotta do...
is just sell off|a few of these critters__
Stop right there, Sam.
They're family.|You don't sell family.
Hohohold your horses, Pearl.
Now you get,|before I start using words...
no good woman should ever use.
Don't bust your gusset, woman!| Go on, Sam!
It is still my property!|Now get!
I said, get!
I was just tryin' to help!
That sure took the starch|right out of me.
I am sorry, girls.
I'm just plum out of ideas.
Well, I think we all know|what happens now.
Well, I think we all know|what happens now.
Uh, Jeb, don't start.| Now we all get eaten.
Jeb?| What? What?
You don't think people in town|eat animals?
But who would eat a chicken?|Heh heh.
Come on, guys. There must be|something we can do.
What? What could we do?
This just isn't fair.| Fair!
Good call, Curly!
Ollie.| Ollie.
Uh, what is?
Listen. What would you say|if I told you...
that you could win big money__
and see|beautiful downtown Chugwater__
if you went to the County Fair?
Thank you for your input, but__
Come on! Let the new cow talk!
New cow! New cow! New cow!
Come on, Mrs. C. You've got|a real goodlookin' bunch here.
I see some real potential.
Aw, shucks.
Now, the fair is two weeks away.
I say we go to town, butter up|that sheriff's horse...
and get him|to give us more time.
What are we waitin' for, Maggie?|Let's go.
That's right.|What do you say, Caloway?
Bah! Absolutely not.
I will not abandon Pearl|in her hour of need...
for such a ridiculous plan.
She would be devastated|if she found us missing.
As far as I'm concerned,|that's not an option.
All right. Suit yourself.
Come on, Grace.|We've got a farm to save.
Oh, you'll have to excuse her.|She's just a little tense.
Tense. What's her specialty,|sour cream?
Going to town.
Of all the illconceived I__
Now, don't look at me|so crossly.
I know what|you're going to say__
that Maggie and Grace|will need someone...
with my eye for detail...
to keep them|on the straight and narrow.
Say no more. I'll go.
Now, tut tut. No mushy|goodbyes, my little ones.
You know how I get|about overly emotional displays.
Ahem. Ladies?
Mrs. C.
Well,|what made you change your mind?
I'd rather not talk about it.| It's a chick thing.
Good luck, girls!
See ya!| Bye!
They're stew meat.| Hurry back!
¤ She'll be|comin' 'round the mountain ¤
¤ She'll be comin'|'round the mountain ¤
¤ She'll be comin' 'round... ¤
She better hurry up|around that mountain...
'cause I cannot take this|much longer.
Maggie, may I be frank?
Only if you let me wear the hat.
Ahem. Lowbrow remarks|may work for you...
but we prefer|the gentle approach.
Well, she better|stick a sock in it soon.
The vultures|are starting to circle.
Hey, she's not dying!
You sure? We could wait around!
¤...no, nothing,|when she sees Grandma ¤
¤ No more food for her ¤
We'll keep you posted!
False alarm, Clem!
Roger dodger, out like the wind!
Hey, Maggie, Mrs. C?|How do we find...
the sheriff's office|when we get into town?
Elementary, my dear Grace.
If we find Buck,|we find the sheriff.
That horse is a legend|in his own mind.
Ah ha ha ha ha!
Ah ha ha ha ha!
So, you think|you got the drop on me?
Well, think again.
Wahoo!
Wah! Wah!
Wah!
Yahhoo! Hyah!
Haaay! Jump back! Kiss myself!
Buck. Earth to Buck? Buck!
It's your move.
Ohh...great.
You were sleepfighting again.|Almost threw a shoe.
Ohh. Sorry. Heh.
It just__it seems like|all the other horses...
are out there fighting bad guys|and takin' names!
Uhh! Who put this here?
Oh, Buck,|this ain't no Dodge City...
but we get our share|of excitement.
Hey, sheriff!
Been waitin' a long time|to give you this!
Telegram!
Oh, howdy, Morse.|What you got there?
Hmm. "Got Evil Eye Joe. Stop.
"Bringing him today. Stop.
Have money ready. Signed, Rico."
Ha! Oh, yeah!|Rico caught another one already.
Might as well give him|the key to my safe.
You hear that, Rusty?|Rico's comin'.
Yeah, Rico.|I'm old. I ain't deaf.
Boy, wouldn't that be the life?
Ridin' with Rico,|cleanin' up the west.
Kickin' badguy behind!|Whoo! Wahyah!
Watch out, sucker!
All right, girls.|We're goin' in.
Look! There's no fences.
What keeps the people|from roaming?
They appear to be domesticated.
It doesn't feel dangerous|at all.
It's perfectly safe.|Quiet as a farm at milkin' time.
What was that?
It's a gunfight!
Aah! Hit the dirt!| Who lives like this?
What do we do? What do we do?
Look,|there's a star on that door!
That must be|the sheriff's office.
Move, ladies! Move!
¤ Swivel your hips, ooh!|Give 'em a grind ¤
¤ Shimmy and shake|and leave your troubles be__ ¤
Ha ha ha!| Ha ha ha!
Whoa!| Get those cows off the stage!
Maybe we came at a bad time.
Charge!
Ha ha ha!| Ha ha ha!
How dare you?| Oh!
Whoaohoh!
Daddy?| Son!
I say! Aah!
Aah! Oh! Ow! What did I do?
That does it!
Hoof it on out of here, ladies!
Go on!| Oh, come back!
That was the best dang show|we ever had!
Aw, you've been on the trail|too long, you old coot.
Ohh. What kind of|sheriff's office is that?
Dancing girls, gambling...
Ha! How does he ever|get any work done?
If that's the sheriff's office,|this town rocks.
Well, if it isn't|three maids amilkin'.
You girls a little far|from home, aren't ya?
Well, if it isn't|the phony express.
We want a word with you|about this.
What's that?| What is that?
I believe you left this|on our farm.
Wai__whoa, whoa, whoa, whoa.|Wait a minute.
The place went bankrupt.|Your farm is history.
Don't you heifers get it?
Hold on, you two!
Give us two more weeks...
and we'll have at least|sixty bucks in prize money to__
Ahahah. You got three days|to pay or get on your way.
And sixty bucks don't cut it.
Looks like you need about...
Hmm, I'd say...
seven hundred and fifty of 'em.
But, Maggie, where are we|gonna get all that money?
Well, maybe Maggie|can just pull it out of her ear.
Hey, watch it, Caloway.
Rico.| Rico.
Rico.| Rico.
Who is that?
Sorry.
Don't you know a hero|when you see one, huh?
That's Rico...
the best dang bounty hunter|this side of the Pecos.
I could guess|from here to tomorrow...
but I don't know|how you do it, Rico.
Mmf!| Where's my money?
Well, all right,|I got it right here for you.
Hey, they're giving away|free money!
Oh! Maggie!
So, who else is out there?
The only varmint left...
is that lowdown,|goodfornothin' Alameda Slim.
Cattle rustler.
What's the bounty?| $750.
I got it!
Why don't we go nab|that Alameda Slim...
and use the reward money|to save the farm?
Oh, that is a sensible idea.
I knew you'd love it!
Tch. Don't they have sarcasm|where you come from?
Oh, wake up and smell|the alfalfa! It's perfect!
I'm gonna need a fresh horse.
Hmm, a horse. A horse.
Let me think.
I reckon you'd want|a fast horse, huh? Real fast?
Course, he'd also have|to be able to go...
for days|without food or drink...
stealthy,|surefooted in any terrain...
Well, huh...
Look at me!| What about that horse?
What, you mean Buck here?
Eee!| Boy, I don't know.
Buck's fast, all right,|but he's kind of a handful.
He'll do.| Well, suit yourself.
Hey, Rusty!
Rico's saddle!|I'm wearing Rico's saddle!
I'm wearing Rico's saddle!
Great. I'll leave you two alone.
Ohh, oh, no. No, no, no.
There is no way|in heaven or earth...
that cows can catch an outlaw.
Look, all we've got to do...
is follow this chuck wagon|to a cattle drive.
Ahh. And then, you see...
we let the bad guys come to us.
Oh! We've|no reason to believe...
this chuck wagon is heading off|to a cattle drive.
Hey, Tommy!|Have fun on that cattle drive!
All right, then. Mmhmm.
I think it is|headed toward a cattle drive.
Shh. We are not following|this wagon, and that is final.
Come on, Caloway. It'll be fun!
Did you just hit me?| Kinda.
Well, stop it.| Why?
Because I don't like it.
Oh, no. Not the hat.
What? What about the__
All right, all right...
violence is not going|to solve anything.
Why don't we all take|a deep cleansing breath__
Yaah!| Yaah!
Hey, now! Mud wrestling!
Ha ha! Hey, hey!|Watch the saddle!
What in tarnation?
Maggie, for the last time...
I will not be roped|into this scheme.
Come on, you crazy heifers!
Come on! Dagnabit!
Hey, partner,|curb your livestock.
This town is clean!
Giddyup!
Ack!
Not exactly what I had in mind,|but this'll work.
Well, it doesn't work for me!
Adios, Buck.|Take care of Rico now.
Hasta la vista, heifers!|Hoo hoo!
¤ Oh, give me a home ¤
¤ Oh, give me a home ¤
¤ Where the buffalo roam ¤
¤ And the deer__ahem__|and the antelope plaaay ¤
¤ Where seldom is heard ¤
¤ A discouraging word ¤
¤ And the skies|are not cloudy all day ¤
¤ Home, home on the range ¤
Sold!| What was that?
It's a farm auction, ladies.
And that's the last|of the furniture.
The final item|to be auctioned...
is this piece|of real property...
known heretofore|as the Dixon farm.
Do I hear 425? 425!|Do I hear 450? 450?
What's going to happen|to the cow who lived there?
She'll be OK.
How do you know?| You're lookin' at her.
This was your farm?| Mmhmm.
We had, like, a family, too,|you know.
What happened?| Alameda Slim happened.
Sold to Mr. Yancy O'Del!
Pleasure|doing business with you.
Cattle drive. Told ya.
You both owe me a dollar.
Step lightly, girls.
The male of the species|can be extremely hostile.
Oh, come on, Caloway.
It's not like they haven't|seen a cow before.
Hey, Barry.
What? Huh?| Check it out.
Ooh, dairy cows!
Oh, hey, how's it going?
Oh, hello. Let me guess.|You're a Taurus.
Look, just keep moving|and avoid eye contact.
Pardon me, but what are|three lovely ladies like you...
doing on a drive like this?
Just ignore them,|and perhaps they'll go away.
Oh, they seem like nice guys.|Maybe they can help us.
Why, sure we can help you.
Maybe we can help each other.
Hmm?| Hmm?
Look, loverbull,|we're here strictly on business.
Ooh, sounds pretty exciting.|What kind of business?
We're looking for a cattle|rustler named Alameda Slim.
Grace! Shh!| Grace! Shh!
Hey, it doesn't hurt to ask.
Slim? Oh ho ho ho!
Why, Slim's just|a scary bedtime story...
to get little calves to behave.
What was that?
It must be Slim and the Willies.
Slim and the Willies?
Don't worry, darlin'.|I'll protect you.
You have exactly two seconds|to remove your hoof...
before I snap it off|at the knee.
Oh, uh, sorry, ma'am.|I thought you were the blonde.
Ooh!
Come on, girls.|It's time to lose these ropes.
Where you going? Hoyah! Hyah!
Maggie, I'm stuck.| Look out!
Hahh!
It's payback time.
Cover me!| With what?
Howdy, Slim.| Howdy, Slim.
Quiet, you fools.|We've got work to do.
Now listen up.
¤ There are crooks|in this here west ¤
¤ Who have claimed|to be the best ¤
¤ And they think they wrote|the book on how to rustle ¤
¤ Well,|as good as they may be ¤
¤ Not a one's as good as me ¤
¤ And I barely have to move|a single muscle ¤
¤ They call me mean, boys ¤
¤ Depraved and nasty, too ¤
¤ And they ain't seen, boys ¤
¤ The cruelest thing I do ¤
¤ You see I|yodeladleeedleidleodle ¤
¤ The sweetest way of rustlin'|yet devised ¤
¤ 'Cause when I|yodeladleeedleidleodle ¤
¤ Why, looky,|how them cows get hypnotized ¤
¤ He don't prod,|he don't yell ¤
¤ Still he drives|them dogies well ¤
¤ Which ain't easy|when your chaps are labeled ¤
¤ XXXXL ¤
¤ Yes, if yer lookin'|from a bovine point of view ¤
¤ I sure can|yodeladleeedleidle ¤
¤ Yodeladleeedleidle ¤
¤ Yodeladleeedleidleoo ¤
Here we go, boys!|5,000 cattle in the side pocket!
Maggie! Mrs. Caloway!|Snap out of it!
¤ A sound that cattle|truly take to heart ¤
¤ Yeah, I can|yodeladleeedleidle ¤
¤ Yodeladleeedleidelodle ¤
¤ And smack my big old rump|if that ain't art ¤
¤ He don't rope,|not a chance ¤
¤ He just puts 'em|in a trance ¤
¤ He's a pioneer pied piper|in tengallon underpants ¤
¤ Yep, I'm the real|riproarin' deal ¤
¤ To those who moo ¤
¤ Thanks|to my yodeladleeedleidle ¤
¤ Yodeladleeedleidle ¤
¤ I got cattle|out the old wazoo, heh heh! ¤
¤ 'Cause I can|yodeladleeedleidleoo ¤
¤ Yodeladleeedleidleoo ¤
Whoa. Ho, boy.
Rico, if you'd just been|a second earlier...
you'd have had that rustler|dead to rights.
You boys see anything|before I got here?
Yeah, we sure did there, Rico.
We were just|settin' down to supper...
when all of a sudden|the lights went out.
All right, what part of|"cover me" didn't we understand?
You guys OK?| I don't know.
I feel like I was dreaming.
Yeah. Slim started singing...
and all of a sudden|I lost track of everything.
Singing? That didn't sound|like singing to me.
And, you know,|I have perfect pitch.
Uh, yes. Grace,|about your perfect pitch__
Not now, Maggie.| All right, show's over!
Oh, no.
You're interfering|with official police bidness!
Ha. Be right with you, big guy.
Buck is on the case.|You know. Whoo!
Don't embarrass me|in front of my partner. Please!
You and he are partners?
So, how does that work exactly?
I mean, do you get to ride him|on odd days or even?
Hey! He chose me specifically...
because I have skills|that are essential...
to capturing our quarry.
Ha ha ha!
Whoo! Smush! Oof!
You boys headed back to town?
Yes, sir. We got to go file|a report with the sheriff.
Give him back his horse.
This one's too skittish|around cows.
And that, girls,|is what makes me and Rico...
equal parts of|one lean mean crimefighting__
machine?
Well, there it is, then.
Well, well, well, stud.
Now, I'm no professional...
but I'd say the only|mano a mano you'll be doing...
is in your dreams.
Oh, look out, Buck.
He's making a move|on your left flank. Kaboosh!
Maggie! Grace!|Leave that poor animal alone.
Buck,|I realize you're very upset...
but if you'd like|to join our group...
and help us bring in Slim,|we'd be happy to have you.
However, there are a few...
angermanagement issues|we need to discuss.
I wouldn't help|you bossy bovines...
if my life depended on it!
You see, that's just|what I'm talking about.
Grace!| Bye.
Come on, girls.| Hmm.
Let's go get Slim.
"Come on, girls,|let's go get Slim."
Cudchewing heifers.
Huh. I can catch that Slim with|one hoof tied behind my back.
Wait a minute. Why don't l?
Yes! Partner or no partner,|that's what I'ma do. Hey!
¤ Ba ba ba ba ba ¤
Hold the horse now.
Aw, forget it.
Definitely bipolar.
Move it, sister!|Hero passing on the left!
Hey, watch it.| Where are you going, hotfoot?
I'm gonna go nab that rustler...
and show Rico|I got what it takes...
so say goodbye to your farm,|girls, because Slim is mine.
It's hero time!
Watch out now! Hey! Get back!
Jump back! Kiss myself! Whoo!
¤ Da da yoo ¤
Oh, this is|a fine kettle of fish.
How can we compete with that?
Look at the bright side, Mrs. C.
Don't forget about|our secret weapon.
Secret weapon?
Who better to catch|a cattle thief than a cow?
Yeah, even you can't argue|with that kind of logic.
OK, maybe you can.
You know, Grace...
Maggie does so love|your singing.
How about a song?
I'm gonna get you for this.
Ha ha! 5,000 Texas longhorns.
Not bad for one night's work.
Pick a color.
I said,|not bad for one night's work.
What?| Thank you.
And judging by the ear mark...
I'd say these are the last|of Big Mike Donald's herd.
Big Mike Donald had a farm?
EIEI__IEIEI__
Ohh...| Ohh...
That's right. He had a farm.|Heh heh heh.
Now that all his cash cows|have disappeared...
that poor sap's|gonna be flat broke.
Perfect time for a certain|upstanding land owner...
to step in|and take all the land.
Aah! Who are you?
What did you do|with Uncle Slim?
Put up your dukes,|Mr. Fancy Britches.
Aahaahaahaahaahaah!
It's me. Hello?
This here|is the disguise I use...
to sneak into|all them auctions...
and buy all the land,|you brainless monotone monkeys.
Shoot, you got to be the richest|land baron in the west.
Yes, but the part|that really warms my heart...
is watching those homesteaders|suffer.
Back in the day, I worked...
the highfalutinest ranches|you ever seen...
but those stuckup ranch bosses|couldn't appreciate my talents.
Maybe they just didn't like|your singing.
My singing?
Songbirds sing.
Saloon gals sing.
Little bitty snotnosed|children sing.
I yodel!
And yodeling is an art!
Well, maybe they just|didn't like your yodeling.
He didn't mean it, Uncle Slim.
Everybody likes yodeling.
Hmm?
Why, it's one of the funniest,|cornball, goofy, silly sounds...
in the whole west.
Yaah! Aah! Yaah!
Uh, Gil?| Uhhuh?
Am I correct in assuming|that each and every time...
we brought a herd back|to this secret lair...
you've managed to sit|in the exact same spot...
blocking that choice|piece of property from my view?!
This is my comfy place.
What? Aah!
It's called|Patch of Heaven, Uncle Slim.
Goes on auction|Thursday morning.
Perfect. Pencil it in.
Thursday morning__right after|we sell off this herd.
But it's just|a little old dirt farm.
Ah, what's the difference?
When you're talking revenge,|every last acre counts.
I don't get it.
Weren't the cows|supposed to come back?
Daddy, what's going to happen|if they don't come back?
Oh, but they are coming back.
Hogwash! We all know|they're never coming back.
What? Ooh! Ooh!
You don't know that, Jeb.
Everybody knows that bovines...
are the most intelligent,|crafty animals in the west.
Yeah. He's right, you know.
It doesn't take a cow|to figure out...
they saw|the writing on the wall...
and flown the coop|while the getting was good.
What?
Oh, no!|They tricked us and deserted us!
No, no. AudAudrey.
Excuse me. Excuse me.
Excuse me!
Oh, uh, let's not forget|who we're talkin' 'bout.
Audrey, remember when|Grace helped you figure out...
why you crossed the road?
And, Jeb, Miss Caloway|knew just what to do...
when your head got stuck|in that spittoon.
Get off my case!
And Maggie|was gonna make us all winners.
I truly believe|there ain't nothin'...
those three cows can't do.
Well, whatever they're gonna do,|they better do it soon.
I'm so very sorry, Pearl.
It's a real shame. It is.
Ollie,|I don't know what's worse__
Losing my farm|to the highest bidder...
or knowing that__that my girls|are lost and alone out there.
Yeehaw!| Come on, girls.
Either|I'm getting good at this...
or his scent|is getting stronger.
Go get him, Maggie.|Look out, Slim!
No. It can't be.| We're on your trail!
Hoo hoo!
This has Buck|written all over it.
We're not gonna let|this dumb old trick stop us.
Sooner or later, all these paths|will hook up, and then...
Oh, no, the tracks!
Hurry up, girls.|Don't lose that trail.
What trail?|I can't see anything.
Look out!
Oh! Flash flood!
Get to high ground!
Oh.| Maggie!
Maggie!
No! Come on, girls,|we can't give up!
Maggie, that's enough.|The minute this lets up...
we're heading straight home|to Patch of Heaven.
But what about catching Slim|and collecting the reward?
We never had a prayer...
of catching Slim|in the first place.
This whole ridiculous plan...
is just so you can get revenge|on those cattle rustlers.
Hey!|For your information, duchess...
this whole ridiculous plan|is about us saving our farm.
Huh. Our farm might've had|a fighting chance...
until you came along.
What's that supposed to mean?
Strutting around with|your vulgar showcow behavior.
Look, I was just having__
Wasting our time|on your foolish plans.
Through the years,|Patch of Heaven...
has survived every hardship|that nature can dish out...
but you, Maggie...
are the biggest catastrophe|to ever hit our farm.
Well, if that's the way|you feel about it...
maybe we should just go|our separate ways.
Now, that's the first|good idea you've ever had.
Fine!| Fine!
Fine!| Fine!
Yeah. Fine.
It's not like your farm...
was ever gonna feel like home|to me anyways.
¤ Rain is pourin' down ¤
¤ Like the heavens|are hurtin' ¤
¤ Seems like it's been dark|since the devil knows when ¤
¤ How do you go on|never knowing for certain ¤
¤ Will the sun|ever shine again? ¤
¤ Feels like it's been years|since it started to thunder ¤
¤ Clouds are campin' out|in the valley and glen ¤
¤ How do you go on when|you can't help but wonder ¤
¤ Will the sun|ever shine again? ¤
¤ What if the rain|keeps fallin'? ¤
¤ What if the sky|stays gray? ¤
¤ What if the winds|keep squallin' ¤
¤ And never go away? ¤
¤ Maybe soon the storm|will be tired of blowin' ¤
¤ Maybe soon|it all will be over, amen ¤
¤ How do you go on if|there's no way of knowin'? ¤
¤ Will the sun ever shine? ¤
¤ Wish I could say ¤
¤ Send me a sign ¤
¤ One little ray ¤
¤ Lord,|if you're listenin' ¤
¤ How long until then? ¤
¤ Will the sun ever shine ¤
¤ Again? ¤
Maggie. Maggie. Maggie.
Wake up.| Check, please!
It tasted a lot better|in my sleep.
Well, I suppose|you'll be off now.
Mmhmm.| Where will you go?
Oh, probably check out|the Grand Canyon.
See Utah before I die.
Wait a minute. Where's Grace?
Hi, there.|Boy, am I glad you guys are up.
Hey, come look at this.
What on earth?|Where did all this come from?
Hey, it's green, it's leafy,|and it's free. Shut up and eat.
Good morning, ladies.
I see you're already|tucked into your appetizer.
Never knew a pretty lady|that didn't have an appetite.
Oh, now, see here, you ruffian__
He's not a ruffian,|Mrs. Caloway.
He's a genuine desert shaman__|our very own wise man.
Shaman, chef, chief cook,|and bottle washer.
I'm a jackrabbit of all trades|and at your service.
Folks around these parts|call me Lucky Jack.
Yep, they used to come|from miles around...
just to get one rub|of my lucky rabbit's foot.
Whoo! Dagnabit!
This happens all the time.|Now, where was l?
Ah. Voila.
Now let me just|get this on the fire...
and it'll be ready directly.
Mmhuh. Ow! Yow!
Look, we don't eat meat.
It's kind of like|a professional courtesy.
Perhaps we'll dine with you|some other time.
You see, Grace and l|are returning to our farm...
to say our last goodbyes.
Yeah. We need closure.
Well, I can sympathize there,|sister, I truly can.
Until recently,|l, too, had a home.
Echo Mine it was called.
Us jackrabbits lived there|for generation after generation.
Till some landgrabbing bandit|moved in...
and flushed us out|like yesterday's oatmeal.
Ahem. Excuse us. My good fellow,|we must be on our way.
Wait! There he is!
Slim! You mean|this nogood varmint...
is hiding out in Echo Mine|right now?
Without a doubt.| Maggie, what are you thinking?
Look, I got a score to settle|with that rhinestone fat boy...
and nothing to lose.
But it'll be dangerous going|after Slim all by yourself.
Hey, I got the rabbit.
That's not all you got, Maggie.|You got us.
Oh, no. No, no, no. No.
We are sticking to our plan|and going home.
Hold on, you two.
As strange as this sounds,|Grace is actually making sense.
Thank you.| You want the money...
and I want to get even|with Slim.
The three of us go together,|and we're sure to get him.
Once you collect the reward,|I'll walk out your front gate...
and I'll stay out of it forever.|Deal?
Your powers of persuasion|are uncanny. Deal.
Ha! Bovine bounty hunters!|Now I've seen everything.
Let's get moving, ladies.
Let's get moving, ladies.
Time for an underground|smackdown. Yeehaw!
¤ Out in the land where|the heroes meet their makers ¤
¤ Out in the land where|the hale and hearty fall ¤
¤ Out where the fearless|get the shudders ¤
¤ Justice is here,|and it's wearing udders ¤
¤ Yeehaw!|The cows are walkin' tall ¤
¤ Home, home,|this ain't it, pal ¤
¤ Home, home,|home on the range ¤
¤ Home, home,|better go git, pal ¤
¤ Home, home,|home on the range ¤
OK, boys, let's go|through it one last time.
Who am I?| Uncle Slim?
Correct! Heh.
Now, I put on my hat...
then I put on my spectacles__
Aah! Hey! Who're you?| Where's Uncle Slim?
Ohh! It's still me!
Can't you stupid|sack of hammers get it right?
Oh, the everpunctual|Mr. Weaseley.
OK, everybody make way...
for the big man|in black market livestock.
Hey, who're you?
All right, come on!
Move it, Bessie, or|I'll tan your hides right here.
I__hey, hey, hey!|Watch the suit! Watch the suit!
Feast your eyes.
5,000 cows on the barrelhead|as promised, Mr. Weaseley.
The name's Wesley.
So, Slim, what do you say|we get a move on...
and load these cash cows|onto the train A.S.A.P., huh?
Let's go.
Yes, yes, of course. Just as|soon as I finish counting. Hmm.
Lucky Jack, you did it!|We're here!
Well,|I take my hat off to you, Jack.
But you've got us here|in one piece.
Well, seein' is believin'.
And I don't believe what I see.
Oh, it's Buck!
Stallion of the Cimmoron.
I'm supposed to be here|just in case...
one of the horses get tired.
Cows only.
Look, friend, you don't|understand my situation.
No, you don't understand...
so I'll say it again.
The only critters|that get by me are cows.
Cows only.
Oh, come on!|Look, cut me a break.
Now what?
Aww, what are you doing here?
Ha ha! Sorry we're late.|We got separated from the herd.
Right this way, little lady.
Tell 'em Junior sent you.
Ohhh...
Howdy, partner!| Ahem.
Nice hat, ma'am.| Oh! Cheeky devil.
Excuse me, reject.|Coming through.
Oh! Hey, what gives?!
How come|they got to go through?
They're cows.
What?!|But what about the rabbit?
Well, obviously,|he was with the cows.
Ha! I'm with the cows, too!
Yeah! Hey! Hey, cows! Wwait up!
You got to tell this guy|you know me!
See, Junior, we're old friends!
Come on, Margie! Uh, Gretchen!|Miss, uh__uh, Hat Cow!
Come on,|it's your old pal Buck, see?
Buck...Buck...
Oh, Buck!
Nah, doesn't ring a bell.
No, no, no, wait!|Hey, come back! No!
Hang on__hang on a second.|Heh heh heh.
They're just kidding.|You see, if you could__
Oh, hey! Hey!|Hey, cows! Cows! Oof!
Don't make me hurt you.
Heh heh.
Rico.
I gotta go, but let's throw on|the old feedbag sometime.
Stay cool.|Ha ha ha! It's hero time.
So what's the plan?
Well, let's see...
You two get his attention|while I sneak up behind him...
and then|I'll knock him into the cart...
and then we'll rope him up|and wheel him to justice!
And for extra measure...
how about we conk him|on the noggin with this?
You go, cowgirl!|That's usin' the old hat.
Whoa, whoa, whoa!|Now, you lost me here, missy.
Look, Jack, it's simple.
Cart, smack, rope, roll,|justice. Come on, Jack, focus.
Now is not the time to get|all scatterbrained and flaky.
Oh, good, I'm not too late.
Sorry. Still stakin' out|your quarry, huh?
Yeah, pretty much. Why?
Listen, I came to warn you, one|equine to another, about Rico.
As soon as he nabs|that rustler...
he's gonna be in a big hurry|to collect that reward.
So?| So?!
Once he catches his man, that's|when the horsewhip comes out...
and he's not shy|about using it, either!
Horsewhip?| Horsewhip!
And not only are you|gonna be carrying Rico...
but that rustler as well.
Have you seen that guy?|He's huge!
What should I do?
Run!| OK.
Yeah, run like the wind,|partner, and save yourself!
I'm going!
Go on, take off! Fade!|Ride into the sunset!
All righty, I'm outta here!| Aah! Scram!
OK, thanks, buddy!|I owe you one!
Godspeed, my friend!
So long, sucker! Ha ha!
He must be takin' stupid lessons|from that buffalo.
1,420...| 4,334...
Can't you morons|count to yourselves?
Come on.
Gotta start all over!
There he is.| Come on, let's go!
Hold on!
You're both forgetting|Slim's hypnotic control...
over those|with less than perfect pitch.
Jack, I hope you can forgive me.
For what, missy? Aah!| For that.
Now, you watch it there, toots!
Grace, how practical!
Done countin'!
What do we got?| 4,997.
What?| Huh? Wait, wait, what?
I thought you said 5,000 even.
Of course I did. Gil must've|just miscounted, that's all.
Huh?
There's one up there!
The others can't be far behind.
Just you watch.
You're gonna like this.|Yodeling's an art.
Huh?
Ha ha ha!|What's the deal, Slimbo?
Maybe she wasn't an art lover.
Philistine!
Shut up, you greenhorns!
A bovine ain't been born|that can resist my charms.
Ahem.
Watch your back, Uncle Slim!
Got you!|Where do you think you're going?
Now, Jack!| OK!
What in the rootin'tootin'|blazes is goin' on here?!
Uncle Slim! Uncle Slim!
Let's get outta here!
Aah!| Come back here, dog meat!
Jackpot!| We got him now!
Well done!| Watch out!
It's Buck!
Hey, Casey Jones...
grab the bills|and fire up the getaway express!
Uncle Slim! Uncle Slim!
I gave up clown college|for this?
Aah! Aah! Ooh! Mama!
It's Slim! I got Slim!|Rico's gonna be so proud of me!
Thank you!
Whoa! Whoa! Ooh! Leave me alone!
Yaaahhoohoohooey!
Sorry.| Uncle Slim! Uncle Slim!
Quick, girls, in here!| Ooh!
Hey!
Huh?
That was Rico!
What in blue blazes?
I'll knock you|into next Tuesday!
Come back here!
Whoa! Whoa!| You're going down!
Junior! Junior!
Oh! Whoa!| Junior!
Juniooor! Whoohah!
Get this off of me!| Uncle Slim! Uncle Slim!
Rico's saddle!|I'm wearing Rico's saddle!
Uncle Slim! Oof!| Ohh!
Surprise!| Oof!
We made it, girls!|We made it!
Three cheers!| Hiphiphooray!
Ladies, we got company!
Whoa! Stop! Stop! Hit the brake!
Look out!
Yaah! Dagnabit!
I guess I gotta do everything|around here myself!
Call me crazy, but I think|these cows got it in for me.
Maybe they just don't like|your singing.
Shut up! Ahem.
Mr. Weaseley,|my money, if you please.
Heh heh heh. I was just|keeping it safe for you, Slim.
Sure you were.
Protecting my investments|is what I pay this fellow for.
Mr. Weaseley, let me present...
the most traitorous,|doublecrossin' gun for hire...
that I've ever had the pleasure|to call partner__Rico.
You're too kind, boss.
No, it can't be.
His reputation as|a bounty hunter is wellknown...
but lately he's been doing|a little moonlighting...
and covering my tracks.
Rico's going to see you|to the border...
so that nothing else goes wrong.
Now, if you'll all pardon me...
there's|a little Patch of Heaven...
on the auction block|this morning.
He's going to buy our farm!
Adios! Yeehaw!
I don't know|how you got here, skittish...
but stick with me,|and you may get to like...
the other side of the law.
Get on there! Hyah!
All right, come on! Come on!
Move it, Bessie! Get in there!
Hurry up!|You don't want to be late...
for that big roundup|in the sky!
Hah! Skittish, whoa!
Whoa! Whoa! Whoa! Whoa!
Get in there!|Come on, you stupid cows!
Come on!
Lovely.|Now get the engine fired up...
and let's make tracks.
Huh?
Make a break for it,|ladies! Run!
Whoa! Hah! Skittish, whoa!
Buck, have you gone crazy?!
Now, that's entirely possible!|Yo!
Or maybe I just figured out|who the real heroes are!
Wait! What if this is|some kind of trick?
Whoo! Whassah!
Oh, this isn't a trick!|It's a miracle! Come on!
So you think|you got the drop on me...
well, think again! Hyah!
Whassah!
This is useless.
Let's put our heads together.|More brains and less brawn.
All right!
OK, Caloway, fetch!
Kaboosh!| Hyah!
Ha! Lucky shot!
Mother of mercy.|Is this the end of Rico?
Wow! Bravo!
Bravo! You stopped Rico cold!
Aw, shucks. T'weren't nothin'.
Fat lot of good it done us.
Alameda Slim|has already flown the coop.
She's right.
Unless we sprout wings, we'll|never make it back in time.
I can't believe|what I'm hearing.
This train|goes right by Patch of Heaven.
What is in the cud|you've been chewin'?
How are we supposed|to drive that thing?
How? How? I'll tell you how!
The same way we walked off|the farm into the unknown.
The same way we fought off|those burly barmaids.
And the same way we braved|the western wilderness...
without the benefit|of food or water.
We caught Slim once,|and we shall do it again!
Who's with me?
Get out of here, you bulls!|Head for the hills! Whoo!
Let's get it on!| Cows rule!
Howdy, darlin'! Down here!
Yeah! Look__look down!|Hello there!
Oh, no!
I got two words for you guys__|cold shower!
We don't have time|for this nonsense!
We have a farm to save!
Well, maybe we can help you.| Maybe we can help each__oof!
Other!| Ohh!
Bye!|Come up and see us sometime!
Grace!
Oh, no!|It's the Morning Express!
There's a switch up ahead!
Way ahead of you, pops!|Hop on!
Come on, mule!| Let's ride!
Yeehaw!
Ha! Ha!
Whoa!| Oh! Whoa! Whoa!
Roadhogs!
See you back at the farm, girls!
Good luck!
This happens all the time.
Sold!|All property and livestock...
Sold!|All property and livestock...
formerly known as|Patch of Heaven...
is hereby sold|to Mr. Yancy O'Del.
Pleasure doing business|with you. Heh heh heh.
O'Del's the name,|foreclosure's the game.
Well,|just set yourself over yonder.
Sign this deed,|and the property is all yours.
Much obliged, sheriff.
Ha ha ha!
There it is!| Home and hearth!
And a holy hallelujah|of a curve!
Oh, quick, the brakes!| No time for that!
But won't we jump the tracks?| We are makin' our own tracks!
This is going to be messy!
Hee hee hee! The whole territory|belongs to me. Huh?
Five cents for these chicks.
Come on, now,|do I hear two cents?
Behind you!| Bbehind you!
Whoa! Whoa! Hold your britches!|Come on, now!
Whoa! Run for your lives!
Watch yourself!
What's the idea of crashing|your train on my property?
What? Uh...
It can't be!
Hold it right there!
Piggies, it's time to open up|a can of whoophide!
Unh! Who the__Oof! Ow! Aah!
Oh! Get away from there! Aah!
Oh, come on! Ow! Oof!
You wanna get nuts?|Let's get nuts!
It's Alameda Slim!
You think you've won?
It ain't over|till the fat man sings!
Alameda Slim,|you're under arrest.
Nobody messes|with Pearl's girls!
Say, girls, got milk?| Buck!
Just kidding.
Take him away, boys!|Hope you like stripes.
Pearl, your cows can't do much|with Slim's reward money.
Think you can find|some use for it?
Whooeee! My farm is saved!
Where's Maggie?
I can't believe she just left.
I'm gonna miss her.
So shall l, Grace.
Her brash manner,|her bullheadedness.
She risked her life for us,|and who are we but strangers?
We were privileged to know her.|She was a cow like no other!
Right down to her appalling|bodily eruptions.
Ahh, that was good!| Maggie!
I was just having|one for the road...
when I heard|all the nice stuff...
you guys were saying about me.
You know, maybe I could|hang around a while.
How about forever?| Oh!
Hmm.|Well, it's your call, Caloway.
Is this barnyard big enough|for the both of us?
Only if you let me wear the hat.
Yeehaw!
Come on, move your hides, girls.
Last one to the barn|sleeps standing up!
OK, everyone, big smiles!
OK, everyone, big smiles!
"So it was that Alameda Slim...
"the most notorious|and feared cattle rustler...
was apprehended and unmasked|by three unusual dairy cows. "
Hey! Dagnabit, Jeb!
How many times I got to tell you|to wait your turn?
How many times|have I got to tell you...
to get out of my barrel__
Hey, dagnabit! You ornery ol'__
It's so nice that Jeb|finally found a friend.
Here they come, everybody!
Well done!| Ha ha ha!
Well, hi ho, ladies!
Hey, Barry, three queens,|two kings, hmm?
Full house.
And the joker is wild.
Oh, yeah.
¤ Darlin', I swear ¤
¤ Once you been there ¤
¤ There ain't a view|beneath the blue ¤
¤ That could ever compare ¤
Hyah! Hohaa!
¤ The only thing missing ¤
¤ Is you as my guest ¤
¤ On a little Patch of Heaven|way out west ¤
¤ Why don't you come visit? ¤
¤ There's room in the nest ¤
Yeehaw!
¤ On that little|Patch of Heaven ¤
¤ Way out west ¤
¤ Come with me ¤
¤ Let's go wander ¤
¤ Far beyond|the wild blue yonder ¤
¤ Out where stars roam free ¤
¤ Though the journey's|far from breezy ¤
¤ Stick with me,|I'll make it easy ¤
¤ You can depend on me ¤
¤ Yeah, there's|a long road before us ¤
¤ And it's a hard road,|indeed ¤
¤ But, darlin', I swear ¤
¤ I'll get us there ¤
¤ Wherever|the trail may lead ¤
¤ Once we cross|that far horizon ¤
¤ Life|is bound to be surprisin' ¤
¤ But we'll take it|day by day ¤
¤ Never mind|the wind and weather ¤
¤ If we walk that trail|together ¤
¤ Somehow we'll find our way ¤
¤ Yeah, there's a long road|before us ¤
¤ And it's a hard road,|indeed ¤
¤ But, darlin', I vow ¤
¤ We'll get through somehow ¤
¤ Wherever|the trail may lead ¤
¤ Can't tell you|when we'll be there ¤
¤ It may take all our lives ¤
¤ We're headed for|that great unknown ¤
¤ We'll soon be walking free|there ¤
¤ Till that day arrives ¤
¤ At least we won't be|travelin' alone ¤
¤ And there's|a long road before us ¤
¤ And it's a hard road,|indeed ¤
¤ But, darlin', don't fear ¤
¤ 'Cause I'll be right here ¤
¤ To give you|the strength you need ¤
¤ And through the whole ride ¤
¤ I'll be by your side ¤
¤ Wherever the trail|may lead ¤
¤ La la la la ¤
¤ La la la ¤
¤ La la la ¤
¤ La la la ¤
¤ La la la ¤
¤ When you're sad ¤
¤ When you're feeling low ¤
¤ When you're hurt ¤
¤ And don't know where to go ¤
¤ Think of me ¤
¤ There I'll be ¤
¤ Anytime you need a friend ¤
¤ When you're down ¤
¤ And your luck runs out ¤
¤ Or if you're in trouble|or in doubt ¤
¤ It's OK ¤
¤ It's OK ¤
¤ Turn my way ¤
¤ Anytime you need a friend ¤
¤ When you're scared ¤
¤ I will stay with you ¤
¤ When you feel|you're fallin' ¤
¤ I'm there for you ¤
¤ When your heart breaks ¤
¤ I'll ease your aches ¤
¤ Whatever it takes ¤
¤ I'm in ¤
¤ I'm in ¤
¤ Anytime you need a friend ¤
¤ La la la ¤
¤ La la la ¤
¤ La la la ¤
¤ La la la ¤
¤ All our lives ¤
¤ Anywhere we are ¤
¤ Anywhere we are ¤
¤ Just reach out ¤
¤ I'll never be too far ¤
¤ Come what may ¤
¤ There I'll stay ¤
¤ Anytime you need a friend ¤
¤ When you're scared ¤
¤ I will stay with you ¤
¤ When you feel|you're fallin' ¤
¤ I'm here for you ¤
¤ When your heart breaks ¤
¤ I'll ease your aches ¤
¤ Whatever it takes ¤
¤ I'm in ¤
¤ Whatever it takes ¤
¤ Anytime you need a friend ¤
¤ La la la ¤
¤ La la la ¤
¤ Anytime ¤
¤ Anytime you need ¤
¤ A friend ¤